name: Build Windows EXE

on:
  workflow_dispatch:  # para lanzarlo manualmente
  push:               # también compila si subes cambios

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build exe
      run: |
        pyinstaller --noconsole --onefile main.py --name LabDental

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: LabDental-exe
        path: dist/LabDental.exe
